### ISSUE TITLE
feat: Use sphinx-like documentation for hover

### ISSUE THREAD

**Issue by WhyNotHugo** [charliermarsh/ruff-lsp#100]
Given this simple type

```py
class Human:
    #: This is the person's name.
    name: str
```

And this code:

```py
h = human
h.name
```

When fetching the "hover" information (e.g.: `textDocument/hover`, `vim.lsp.buf.hover()` on neovim) with the cursor on `name` this shows the documentation for the type (e.g.: `str`) in this case.

I think that it would be very useful to show the documentation right above the field, instead of the documentation for type type. This particular format is used by sphinx, so a lot of code-bases (e.g.: Django) use this to document fields. In many contexts, the docs for the field are far more relevant/useful that the docs for the type (especially so when the type is something like `int` or `str`).

**Comment by jfcherng** [comment]
Is this the job of something like pyright?

**Comment by WhyNotHugo** [comment]
From what I can tell, ruff-lsp is the one responding to the `hover` events.

But if this feels out-of-scope here, I guess it doesn't **need** to be implemented here and can be implemented elsewhere (I'm using `python-lsp-server`, so it might be feasible there).

**Comment by jfcherng** [comment]
Not sure ruff-lsp uses `textDocument/hover` to do what. But pretty sure type hinting comes from `python-lsp-server`, or at least, not from ruff-lsp.

**Comment by WhyNotHugo** [comment]
I agree that this is an odd fit here. I'll close this and think of integrating this functionality into `python-lsp-server` instead.

BTW: there **is** some hovering code, but I don't think it's the one responding in this scenario anyway: https://github.com/charliermarsh/ruff-lsp/blob/3cf4485aae75b1617e8a1c5a07b987531f13f455/ruff_lsp/server.py#L249
