### ISSUE TITLE
Passing "settings" causes an error on the language server side

### ISSUE THREAD

**Issue by yaegassy** [charliermarsh/ruff-lsp#11]
## Description

The `ruff` command that `ruff-lsp` executes by default uses the command bundled with `ruff-lsp`.

For example, when using a `ruff` installed in a project (venv), it seems to be adjustable in the `settings`, so I tried it.

After checking the code, it seems that the `settings` key in the `initializationOptions` sent by the language client can be adjusted, so I set it up.

- <https://github.com/charliermarsh/ruff-lsp/blob/e2dd69680f0ab722ec7f6af91da00013412d9e78/ruff_lsp/server.py#L503>

I checked the output of the language server from the language client and it seems that there is an error and the settings are not reflected.

### Error

```
// ...snip
Traceback (most recent call last):
  File "/Users/yaegassy/.local/src/ruff-lsp/venv/lib/python3.11/site-packages/pygls/protocol.py", line 84, in decorator
    self._execute_notification(user_func, *args, **kwargs)
  File "/Users/yaegassy/.local/src/ruff-lsp/venv/lib/python3.11/site-packages/pygls/protocol.py", line 228, in _execute_notification
    handler(*params)
  File "/Users/yaegassy/.local/src/ruff-lsp/venv/lib/python3.11/site-packages/ruff_lsp/server.py", line 504, in initialize
    _update_workspace_settings(settings)
  File "/Users/yaegassy/.local/src/ruff-lsp/venv/lib/python3.11/site-packages/ruff_lsp/server.py", line 540, in _update_workspace_settings
    key = uris.to_fs_path(setting["workspace"])
                          ~~~~~~~^^^^^^^^^^^^^
```

There is an error here.

- <https://github.com/charliermarsh/ruff-lsp/blob/main/ruff_lsp/server.py#L540>

## Misc

I use Neovim and use [coc.nvim](https://github.com/neoclide/coc.nvim), a plugin with VSCode-like LSP client feature. The following is the registration of `ruff-lsp` and setting of path in "coc.nvim" (coc-settings.json).

```jsonc
"languageserver": {
  {
    "ruff-lsp": {
      "command": "ruff-lsp",
      "filetypes": ["python"],
      "initializationOptions": {
        "settings": {
          "path": ["~/proj/check-ruff-lsp/venv/bin/ruff"]
        }
      }
    },
  }
}
```

**Comment by yaegassy** [comment]
Incidentally, although not directly related to this issue, it would be even more useful if ruff installed in the project were implemented to be used preferentially.

For example, create a project (checkcheck) as follows Install `ruff` with `venv`. It would be useful if `venv/bin/ruff` would be preferentially executed if the virtual environment is activated.

```
mkdir -p $HOME/proj/check-ruff-lsp
cd $HOME/proj/checkcheck
python3 -m venv venv
source venv/bin/activate
pip install ruff
```

**Comment by charliermarsh** [comment]
Hmm, could this be improperly overriding the settings in some way? I don't think we want to set those as initialization options. I'd have to play around with it to know for sure though.

**Comment by charliermarsh** [comment]
(I think I have to try it out myself to have an informed opinion on what's going wrong here.)

**Comment by yaegassy** [comment]
Does it work correctly with VSCode and sublime text?

**Comment by charliermarsh** [comment]
Yeah I can set those settings in VS Code, but maybe it's doing something special. Will test it out.

**Comment by charliermarsh** [comment]
(But will have to be tomorrow.)

**Comment by charliermarsh** [comment]
I'm wondering if VS Code handles merging any user settings with the defaults, but other editors don't do that for you.

**Comment by yaegassy** [comment]
I have tried this with my VSCode. I can't seem to use `~` in the path setting. When I listed the full path, it worked in VSCode. I may need to modify the README.

However, it seems that non-VSCode (Vim in my case) is having problems with this issue of `workspace` before the `~` issue...

**Comment by charliermarsh** [comment]
Okay thanks. Will be sure to give this a thorough review tomorrow.

**Comment by charliermarsh** [comment]
Ok, I think I do generally understand what's going on, and you're right that there's a bug here!

VS Code is "special" in that the VS Code "client" sends up a full, valid settings object here. Other editors don't do that, and it's definitely not required, so we need to accommodate those cases.

**Comment by charliermarsh** [comment]
@yaegassy - Are you able to test this with `coc-nvim`?

**Comment by jnns** [comment]
Thank you @charliermarsh. I was not able to get ruff-lsp to work with Sublime Text with a custom path until you merged #15. Now it works!

**Comment by charliermarsh** [comment]
@jnns - Oh, amazing! It was definitely broken before -- glad it's working for you now, that's a good sign :)

**Comment by yaegassy** [comment]
@charliermarsh Thanks for the adjustment. 🙇 I have checked that it is working correctly with `coc.nvim`.

We also checked with Neovim's built-in LSP and another LSP client plugin called `vim-lsp`. Both were confirmed to work properly.
