### ISSUE TITLE
codeAction does not work in Helix editor

### ISSUE THREAD

**Issue by tsugumi-sys** [charliermarsh/ruff-lsp#28]
codeAction does not work in [Helix edito](https://github.com/helix-editor/helix)r.

<img width="185" alt="image" src="https://user-images.githubusercontent.com/61897166/209423589-4ff455ef-d09b-4b3d-83a7-c076db4c65ef.png">

I can select actions but do nothing. I'm searching now but do you have any idea?

I check the output (`actions`) of [here,](https://github.com/charliermarsh/ruff-lsp/blob/c4ecadde49f19c9f16fcf3d3910b1f6a71878fc2/ruff_lsp/server.py#L371), the actions returned correctlly.

```
INFO:exampleLogger:[CodeAction(title='Ruff: Organize Imports', kind=<CodeActionKind.SourceOrganizeImports: 'source.organizeImports'>, diagnostics=[], is_preferred=None, disabled=None, edit=None, command=None, data='file:///home/akira/akira/oss/ruff-lsp/ruff_lsp/complete.py'), CodeAction(title='Ruff: Fix All', kind='source.fixAll.ruff', diagnostics=[], is_preferred=None, disabled=None, edit=None, command=None, data='file:///home/akira/akira/oss/ruff-lsp/ruff_lsp/complete.py')]
```

**Comment by tsugumi-sys** [comment]
`CodeAction(..., edit=None, ...)` This is why code edit doesn't happen.

**Comment by charliermarsh** [comment]
I can try it out tomorrow (hopefully). Thanks for reporting.

(edit=None might be ok, because of the “code action resolve” handler, which generates the actual edit after the user selects it (thereby editing lazily).)

**Comment by tsugumi-sys** [comment]
`codeAction/resolve` does not supported yet...
https://github.com/helix-editor/helix/issues/5118

**Comment by charliermarsh** [comment]
Ah dang. Perhaps there’s a way to detect that it’s unsupported and return the edits directly? Or can just wait for Helix to implement that part of the spec.

**Comment by tsugumi-sys** [comment]
I'll search about it: `Perhaps there’s a way to detect that it’s unsupported and return the edits directly?`
And I'll try to fix that issue (but it will take some time because I'm new to Rust and LSP).
