### ISSUE TITLE
`nvim-lspconfig` setting not correctly passing arguments to `ruff-lsp`

### ISSUE THREAD

**Issue by forrestfwilliams** [charliermarsh/ruff-lsp#41]
When configuring the `ruff-lsp` server in neovim using `nvim-lspconfig` I am using the standard configuration shown in the [documentation](https://github.com/neovim/nvim-lspconfig/blob/master/doc/server_configurations.md#ruff_lsp) with the addition of a change to ruff's `--line-length` argument:

```lua
require'lspconfig'.ruff_lsp.setup{
  settings = {
    ruff_lsp = {
      -- Any extra CLI arguments for `ruff` go here.
      args = { '--line-length 120' },
    }
  }
}
``` 

However, when `ruff-lsp` is attached to a neovim buffer, this argument is not respected and the max line length is still 88. I'm guessing there is either a syntax issue here, or the args not being passed to ruff correctly. Any help would be appreciated!

**Comment by charliermarsh** [comment]
I will look into this shortly if my newborn falls asleep 😅 

In the meantime could you try passing the flag and value as two separate elements in the array? Or adding an equals between length and 120?

**Comment by forrestfwilliams** [comment]
No worries! I just tried `args = { '--line-length=120' }` and `args = { '--line-length', '120' }` and neither worked.

**Comment by charliermarsh** [comment]
It turns out you want this:

```
require'lspconfig'.ruff_lsp.setup{
  init_options = {
    settings = {
      -- Any extra CLI arguments for `ruff` go here.
      args = { '--line-length=120' },
    }
  }
}
```

**Comment by charliermarsh** [comment]
(I'll PR those docs, the plugin was added to `nvim-lspconfig` recently, it used to be the case that you had to register it as a custom server.)

**Comment by charliermarsh** [comment]
(LMK if that doesn't fix it for you and I'll re-open.)

**Comment by charliermarsh** [comment]
https://github.com/neovim/nvim-lspconfig/pull/2363

**Comment by forrestfwilliams** [comment]
This works! Ruff is a great tool. Thanks for creating it and implementing all of the editor integrations. If others have neovim configuration questions, feel free to `@` me.

**Comment by charliermarsh** [comment]
Great! Much appreciated!

**Comment by ristillu** [comment]
Thanks @forrestfwilliams for asking the exact question I was looking for and @charliermarsh for providing the solution.
