### ISSUE TITLE
Do you have any idea for `auto-completion` feature of `ruff-lsp`?

### ISSUE THREAD

**Issue by tsugumi-sys** [charliermarsh/ruff-lsp#47]
I want to use `auto-completion` with `ruff-lsp`.
I'm trying to implement this feature while watching [python-lsp-server](https://github.com/python-lsp/python-lsp-server) implementaions. `python-lsp-server` uses [jedi](https://jedi.readthedocs.io/en/latest/) for auto-completion.

[It works now](https://github.com/tsugumi-sys/ruff-lsp) but sometimes very slow compared to vscode [IntelliSense (pylance)](https://code.visualstudio.com/docs/editor/intellisense#_intellisense-for-your-programming-language) (My editor is helix-editor).

**Comment by ahirner** [comment]
Specifically for helix, multiple LSP support may also fulfil this need: https://github.com/helix-editor/helix/pull/2507
Although, that would inherit the overhead of  `python-lsp-server`.

**Comment by tsugumi-sys** [comment]
Yes, and that also would be because of `jedi` performance.
https://github.com/davidhalter/jedi/issues/1059

**Comment by jfcherng** [comment]
Presumming you off load linting jobs to ruff. Then for autocompletion, you may use pyright, which is far faster than pylsp.

**Comment by ristillu** [comment]
I guess my comment belongs on this topic - I am using neovim with [coq](https://github.com/ms-jpq/coq_nvim). My previous other Python LSP tools provided auto-completion with coq. Those are pyre, pyright and python-lsp-server. ruff-lsp does not integrate with coq out of the box. I'm happy to make some effort to do the integration but have no idea where to start.

**Comment by rchl** [comment]
This server handles linting (at least currently). Why would you expect it to also handle code intelligence including completions? You can always use additional servers for that.

**Comment by tsugumi-sys** [comment]
@rchl

> This server handles linting (at least currently). Why would you expect it to also handle code intelligence including completions? You can always use additional servers for that.

I agree with you.
I'm helix user and I did not know about multiple LSP settings, but I just found this [PR ](https://github.com/helix-editor/helix/pull/2507).

**Comment by ristillu** [comment]
@rchl oh, OK. I guess it's because I stumbled across ruff-lsp via Mason and it's categorised as the same type of tool as the old ones I was using (i.e. LSP), which all plug in to coq and trigger the LSP completions. So I assumed ruff-lsp not only did linting but also some value-adds such as LSP hints to coq. Thanks for the correction.
