### ISSUE TITLE
Lapce Integration

### ISSUE THREAD

**Issue by brezn1** [charliermarsh/ruff-lsp#5]
Any chance to integrate the LSP into the Lapce Editor? https://github.com/lapce/lapce
https://docs.lapce.dev/development/plugin-development

Seems to be a good fit.

**Comment by charliermarsh** [comment]
Yeah looks reasonable. Not going to get it done _today_ but definitely doable.

This looks like a decent template to start from: https://github.com/abreumatheus/lapce-pyright

**Comment by brezn1** [comment]
Thanks!

Somehow related idea:  Lapce is using the volt.toml file for additional plugin-switches/configurations. Would be a nice feat to have some of your favorite switches included, without fiddling in the specific config files. 
![Screenshot 2022-12-19 at 21 35 55](https://user-images.githubusercontent.com/5721488/208517473-21fa04f8-f133-4c70-8d55-8e2d8664a064.png)

**Comment by abreumatheus** [comment]
I'm trying to implement this but I'm having a hard time debbuging. is there any log file?

**Comment by abreumatheus** [comment]
Ready to roll:
https://plugins.lapce.dev/plugins/abreumatheus/lapce-ruff-lsp
https://github.com/abreumatheus/lapce-ruff-lsp

Will include settings via editor config in future version, but feel free to open a PR.

**Comment by charliermarsh** [comment]
Oh rad! Thanks @abreumatheus. I'll give this a spin then add to the docs.

**Comment by charliermarsh** [comment]
@abreumatheus - What was your strategy for debugging this?

![Screen Shot 2022-12-23 at 7 47 31 PM](https://user-images.githubusercontent.com/1309177/209415768-e338c983-f8c4-499e-a80c-e8796501d8eb.png)

**Comment by charliermarsh** [comment]
The plugin is now reporting correctly but it's still erroring on initialization. Any ideas?

![Screen Shot 2022-12-23 at 8 03 39 PM](https://user-images.githubusercontent.com/1309177/209416274-2763be14-c1e6-409d-b548-042e5d7c3928.png)

**Comment by charliermarsh** [comment]
Added a link to the README. Still confused because I'm seeing that initialization failure. But when building and linking the plugin from source, it disappears.

**Comment by abreumatheus** [comment]
My bad! It's not actually an error, it's like a console.log I forgot to remove 😅. I'll make a new release when I get home.
