### ISSUE TITLE
[feature] quick fix to quickly ignore an error

### ISSUE THREAD

**Issue by sbdchd** [charliermarsh/ruff-lsp#50]
With ESlint's VSCode's integration there is an ability to quick fix ignore an error:
<img width="661" alt="image" src="https://user-images.githubusercontent.com/7340772/210187880-391717af-94b2-43ee-8fe0-7a4f9f831682.png">

<img width="617" alt="image" src="https://user-images.githubusercontent.com/7340772/210187863-6db61363-8401-4019-b5e2-c3371a61cd78.png">

Currently with ruff this isn't available 

<img width="648" alt="image" src="https://user-images.githubusercontent.com/7340772/210187855-a4b13143-3f77-42d5-b9d2-61264a378903.png">

Thank you for ruff, it's great!

**Comment by charliermarsh** [comment]
Nice idea, we can definitely support this.
