### ISSUE TITLE
[Feature] Add endpoints specifically for Organize Imports and Fix All

### ISSUE THREAD

**Issue by rockerBOO** [charliermarsh/ruff-lsp#54]
Right now, Organize Imports and Fix All code actions fill the code actions list anywhere in any python code. There are settings to disable these code actions (it seems, I'm new to this LSP). I would like to disable the code actions and make each of these separate commands that could be run. 

For example, in typescript-language-server has [`workspace/executeCommand`](https://github.com/typescript-language-server/typescript-language-server#workspace-commands-workspaceexecutecommand) which allows you to run these specific actions. This allows the functionality of these good code actions, but done separately of the code actions list.

Thanks for this LSP and the great ruff linter.

**Comment by yaegassy** [comment]
I believe it can be implemented in your language client using this code from `ruff-vscode` as a reference. 

- <https://github.com/charliermarsh/ruff-vscode/blob/main/src/extension.ts#L60-L86>

By the way, I use Vim/Neovim and my LSP client plugin was able to handle this.

**Comment by charliermarsh** [comment]
Yeah we do have a dedicated "Fix all" action in the VS Code plugin. I'm not sure that this is solvable in general for all clients since it requires some modifications for the client itself. Where are you using the LSP? (Like, what editor, etc.?)

(Thanks for the kind words :))

**Comment by charliermarsh** [comment]
Ok cool -- does the LSP need a `ruff.organizeImports` action too?

(Separately, I don't think it solves your problem, but note that we do also support `source.fixAll.ruff` and `source.organizeImports.ruff` as aliases of `source.fixAll` and `source.organizeImports`.)

**Comment by rockerBOO** [comment]
I think this would be about what would be needed. I made edits to the `apply_autofix`. `I001` being the code to organize imports?

```python
@LSP_SERVER.command("ruff.organizeImports")
def apply_organize_imports(arguments: tuple[TextDocument]):
    uri = arguments[0]["uri"]
    text_document = LSP_SERVER.workspace.get_document(uri)
    LSP_SERVER.apply_edit(
        _create_workspace_edits(text_document, _formatting_helper(text_document, only="I001") or []),
        "Ruff: Organize Imports",
    )
```

Not following what the source things are. Not seeing them in the code for the LSP inside the server.py, or things that could be them. 

Thank you!

**Comment by charliermarsh** [comment]
Yeah that looks reasonable. Feel free to send a PR.

I was referring to the latter two kinds in this code block:

```py
@LSP_SERVER.feature(
    TEXT_DOCUMENT_CODE_ACTION,
    CodeActionOptions(
        code_action_kinds=[
            CodeActionKind.QuickFix,
            CodeActionKind.SourceFixAll,
            CodeActionKind.SourceOrganizeImports,
            f"{CodeActionKind.SourceFixAll}.ruff",
            f"{CodeActionKind.SourceOrganizeImports}.ruff",
        ],
        resolve_provider=True,
    ),
)
def code_action(params: CodeActionParams) -> list[CodeAction] | None:
    """LSP handler for textDocument/codeAction request."""
    ...
```
