### ISSUE TITLE
not inside window folders

### ISSUE THREAD

**Issue by reagle** [charliermarsh/ruff-lsp#60]
I recently came across ruff and would love to have it in ST4. I normally use SublimeLinter, but would move to LSP for ruff! Unfortunately, true to form, LSP is a nuisance to configure and get working. I following the instructions (install LSP plugin and setup settings file with `"log_debug": true,`:

```
// Settings in here override those in "LSP/LSP.sublime-settings"
{
  "log_debug": true,
  "clients": {
    "ruff-lsp": {
      "command": ["/Users/reagle/.pyenv/shims/ruff-lsp"],
      "enabled": true,
      "selector": "source.python",
      "initializationOptions": {
        "settings": {
          "args": []
        }
      }
    }
  }
}
```

Unfortunately, it's not identifying any errors and I see this is the log.

```
SP: starting ['/Users/reagle/.pyenv/shims/ruff-lsp'] in /Users/reagle/e/clear/data
LSP: ruff-lsp: Supported execute commands: ['ruff.applyAutofix', 'ruff.applyOrganizeImports']
LSP: ruff-lsp: supported code action kinds: ['quickfix', 'source.fixAll', 'source.organizeImports', 'CodeActionKind.SourceFixAll.ruff', 'CodeActionKind.SourceOrganizeImports.ruff']
LSP: ignoring unsuitable diagnostics for file:///Users/reagle/bin/td/extract-dictation.py reason: not inside window folders
```

I'm not sure why its starting `ruff-lsp` in `/Users/reagle/e/clear/data` and I don'T know what window folders it's talking about.

**Comment by charliermarsh** [comment]
Blerg, I'm not sure... I'll try to take a look in a bit. It looks like [this](https://cs.github.com/sublimelsp/LSP/blob/3dd72e4703076ce9aea975504fff2940284b6729/plugin/core/windows.py?q=%22not+inside+window+folders%22+repo%3Asublimelsp%2FLSP#L351) is the raising line.

**Comment by reagle** [comment]
Is this a LSP issue then?

**Comment by reagle** [comment]
I moved to 0.0.17 but still not sure what I'm supposed to do with this?

**Comment by rchl** [comment]
@LDAP has created a https://github.com/sublimelsp/LSP-ruff helper package that simplifies ruff usage.

In your case you were getting this log though:

> LSP: ignoring unsuitable diagnostics for file:///Users/reagle/bin/td/extract-dictation.py reason: not inside window folders

which means that the file you were checking was not part of your project folders. This is part of the ST LSP logic.

**Comment by reagle** [comment]
Thank you.
