### ISSUE TITLE
Support `textDocument/formatting`

### ISSUE THREAD

**Issue by timbedard** [charliermarsh/ruff-lsp#61]
It looks like the only way to have ruff-lsp format a document right now is via a `textDocument/codeAction`. From my experience, most LSP servers allow document formatting via `textDocument/formatting`.

It took me a bit to realize, because the example Neovim config registers a keymap for `vim.lsp.buf.format()`, so I was a bit baffled trying to use that to format a file, as ruff-lsp does nothing when that request is issued right now.

**Comment by kalekseev** [comment]
Not sure what the convention for linter lsps and formatting command but at least something like `RuffFixAll` command would be helpful, this is how eslint do it https://github.com/neovim/nvim-lspconfig/blob/d005193b6476088ff032607baca07b1bbbeb36ee/lua/lspconfig/server_configurations/eslint.lua#L165

**Comment by kalekseev** [comment]
For example if someone setup null-ls with black and ruff-lsp that support formatting then he will need to control which lsp should handle formatting command https://github.com/jose-elias-alvarez/null-ls.nvim/wiki/Formatting-on-save#choosing-a-client-for-formatting

**Comment by kalekseev** [comment]
I think RuffFixAll command should be added to the nvim-lspconfig see my link how eslint do this in nvim-lspconfig.

**Comment by Jackevansevo** [comment]
I'm still seeing this issue. Testing in neovim, using the configuration listed here: https://beta.ruff.rs/docs/editor-integrations/#language-server-protocol-official

Running

```
:lua vim.lsp.buf.format()
```

```
[LSP] Format request failed, no matching language servers
```

I can see https://github.com/charliermarsh/ruff-lsp/commit/9f289ec44bee3c535ed8813603d1202722c1094c got reverted, so unsure whether this is a config issue, or something that hasn't been merged yet.
