### ISSUE TITLE
Loosing internal functionality of SublimeText 4

### ISSUE THREAD

**Issue by fschulze** [charliermarsh/ruff-lsp#62]
I really like ruff-lsp, but when I install it the recommended way, I loose SublimeText internal functionality like showing definition and references on hover over a function/class name and jumping there by clicking. Is there a way to use ruff-lsp and keep those things?

**Comment by jnns** [comment]
It does work for me:

![grafik](https://user-images.githubusercontent.com/206281/216341267-7e087676-0af4-486e-883f-be425ac3175f.png)

**Comment by fschulze** [comment]
@jnns do you have an lsp defined for Python? That looks different than what I get from default SublimeText 4:
<img width="525" alt="Screenshot 2023-02-02 at 15 08 19" src="https://user-images.githubusercontent.com/60921/216346991-cd2e6f22-7e6b-41a0-847f-5d4c85ad0f2f.png">

**Comment by norambna** [comment]
@fschulze I am getting the same results as @jnns, but I also have the "Jedi - Python autocompletion" package installed.

**Comment by jnns** [comment]
> @jnns do you have an lsp defined for Python? 

Please excuse my late reply. I have [LSP-pyright](https://github.com/sublimelsp/LSP-pyright) installed.

**Comment by rchl** [comment]
I'm the maintainer of the Sublime Text LSP and as far as I can see the original issue is that the server announces `hoverProvider` capability but doesn't really provide content when requested. If hover provider is not supported in all cases then it should not be announced.

**Comment by rchl** [comment]
Actually, after looking at the code I can see that it does provide those when hovering over diagnostics.

In that case the behavior is expected that the ST's native functionality is suppressed. If you want to argue about that @fschulze then you can report it in LSP repo although I don't really see a consistent way in which this could be handled.

**Comment by charliermarsh** [comment]
Thanks @rchl. Yeah we provide hover capability in certain contexts, but not as a generic LSP server (e.g., if you hover over a rule name, we show you its definition). I think this works ok in VS Code (you still get hover behavior from Pylance or whatnot even with Ruff installed) though I know nothing about the details, and certainly not enough to advocate that one handling is correct or incorrect.

**Comment by rchl** [comment]
In Sublime Text you also get hover details from other LSP servers (like LSP-pyright) if you have those installed. The author of this issue does not run any other LSP servers besides `ruff-lsp` and expects that LSP fall-backs to native functionality but that is not supported.

So the solution could be to also install `LSP-pyright` which also provides much better "references" than the ST built-in syntax-based functionality.

**Comment by fschulze** [comment]
@rchl it would be great if there would be a fallback to internal behavior if possible. I guess this ticket can be closed, but should I open one for Sublime Text LSP about the fallback?

Looks like I should really look into ``LSP-pyright`` then as well.

Thanks to all for looking into this.

**Comment by rchl** [comment]
If you don't care about the hover functionality that ruff provides then you can add this to `LSP-ruff.sublime-settings`:

```
    "disabled_capabilities": {
        "hoverProvider": true
    }
```

I don't think we'd want to fall back to native behavior in ST LSP when server doesn't provide hover content as that would be inconsistent. You'd sometimes get native hover popup and sometimes the one from LSP.

The native hover popup just provides references to the symbol which is supported (and better) by LSP anyway through keyboard shortcuts or menus.

**Comment by fschulze** [comment]
Thanks! I ended up creating https://github.com/fschulze/SublimeLinter-contrib-ruff instead. Works great in my workflow and combines well with flake8, which I still use as ``black`` isn't used in several codebases I work on.
