### ISSUE TITLE
"interpreter" or "path" in LSP.sublime-settings?

### ISSUE THREAD

**Issue by norambna** [charliermarsh/ruff-lsp#65]
My main OS is Manjaro, which is running right now Python 3.10.9 as its system Python version. And I'm using Sublime Text 4 (4143).
I try to leave the system python untouched and run pyenv and/or venv for my different projects. I installed for example ruff-lsp on a Python version 3.8.16, which was installed via pyenv.

When I start Sublime I get an error saying `The ruff-lsp server has crashed 5 times in the last 180 seconds`
The console shows:
```
LSP: enabled configs: ruff-lsp
LSP: disabled configs: clangd, erlang-ls, gopls, ocaml, polymer-ide, ruby, rust-analyzer, sorbet
LSP: starting ['ruff-lsp'] in /opt/sublime_text
LSP: ruff-lsp crashed (1 / 5 times in the last 180.0 seconds), exit code 127, exception: None
LSP: starting ['ruff-lsp'] in /opt/sublime_text
LSP: ruff-lsp crashed (2 / 5 times in the last 180.0 seconds), exit code 127, exception: None
LSP: starting ['ruff-lsp'] in /opt/sublime_text
LSP: ruff-lsp crashed (3 / 5 times in the last 180.0 seconds), exit code 127, exception: None
LSP: starting ['ruff-lsp'] in /opt/sublime_text
LSP: ruff-lsp crashed (4 / 5 times in the last 180.0 seconds), exit code 127, exception: None
LSP: starting ['ruff-lsp'] in /opt/sublime_text
LSP: ruff-lsp crashed (5 / 5 times in the last 180.0 seconds), exit code 127, exception: None
```

So, LSP is not finding ruff-lsp, right? Under the LSP settings I specify now the path of the Python version that has ruff-lsp and the path of the ruff binary:
```
{
  "log_debug": true,
  "clients": {
    "ruff-lsp": {
      "command": ["ruff-lsp"],
      "enabled": true,
      "selector": "source.python",
      "initializationOptions": {
        "settings": {
          "path": ["/home/myuser/.pyenv/versions/3.8.16/bin/ruff"],
          "interpreter": ["/home/myuser/.pyenv/versions/3.8.16/bin/python"],
          "organizeImports": true,
          "fixAll": true,
        }
      }
    }
  }
}
```

I still get the same error. Are the "interpreter" and "path" settings not working as intended? My solution has been running Sublime with a  `PYENV_VERSION=3.8.16` environment variable. This way Sublime runs in an environment where the default version of python is the one where I installed ruff-lsp.

I consider this a workaround, I would prefer to point to the correct Python version via the "interpreter" and "path" settings in the LSP.sublime-settings.

Any hints why "interpreter" and "path" are not working for me?
Thanks in advance!

edit: instead of dealing with "interpreter" and "path", I just used ruff-lsp's full path under "command" and it worked:

```
{
  "log_debug": true,
  "clients": {
    "ruff-lsp": {
      "command": ["/home/myuser/.pyenv/versions/3.8.16/bin/ruff-lsp"],
      "enabled": true,
      "selector": "source.python",
      "initializationOptions": {
        "settings": {
          // "path": ["/home/myuser/.pyenv/versions/3.8.16/bin/ruff"],
          // "interpreter": ["/home/myuser/.pyenv/versions/3.8.16/bin/python"],
          "organizeImports": true,
          "fixAll": true,
        }
      }
    }
  }
}
```

**Comment by LDAP** [comment]
I belive the `settings` key must be outside of the `initializationOptions` (unlike the README).

There is now also LSP-ruff on package control which should help with the installation.

**Comment by norambna** [comment]
I just tried the [LSP-ruff Package](https://packagecontrol.io/packages/LSP-ruff)! It seems ´initializationOptions´ is needed there, even if the default ´LSP-ruff.sublime-settings´ doesn't show it! I work with a line length of 119, so I use a custom config via args in my user ´LSP-ruff.sublime-settings´.

I tried for example this and it doesn't work:
´´´
{
    "settings": {
        // Custom arguments passed to ruff.
        "args": ["--config=/home/myuser/.config/sublime-text/Packages/User/pyproject.toml"],
    },
}
´´´

But this works!
´´´
{
    "initializationOptions": {
        "settings": {
            // Custom arguments passed to ruff.
            "args": ["--config=/home/myuser/.config/sublime-text/Packages/User/pyproject.toml"],
        },
    },
}
´´´

**Comment by LDAP** [comment]
I tested yesterday with the log verbosity setting and that did work outside of the init options. Can you test that too?

If so, I'll update the LSP-ruff default settings to match the actual behavior.

**Comment by LDAP** [comment]
I tested the interpreter setting in Sublime Text with the latest version of [LSP-ruff](https://github.com/sublimelsp/LSP-ruff), and it does have an effect on ruff-lsp.

You can enable LSP logs in the LSP Settings, and post the log. There should be these two lines:
```
LSP-ruff: Using interpreter executable: <path>
LSP-ruff: Running Ruff with: [<ruff_with_args>]
```

**Comment by charliermarsh** [comment]
Closing since I _think_ this is resolved? :)
