### ISSUE TITLE
Cannot overwrite default settings for `fixAll` and `organizeImports`?

### ISSUE THREAD

**Issue by xulongwu4** [charliermarsh/ruff-lsp#72]
Hi, I am trying to overwrite some default settings of ruff-lsp, but it doesn't seem to work. Can you provide me some guidance on what is the correct way to do it?

What I have done:

I tried both coc.nvim and nvim.lspconfig, and neither of them worked.

In coc.nvim's settings, I added the following:

```json
    "ruff-lsp": {
      "command": "ruff-lsp",
      "filetypes": ["python"],
      "settings": {
        "fixAll": false,
        "organizeImports": false
      }
    },
```

When using nvim.lspconfig, I used the following:

```lua
require("lspconfig").ruff_lsp.setup({
    settings = {fixAll=false, organizeImports=false}
})
```

After I added these settings, I still see `ruff`'s `fixAll` and `organizeImports` in code actions. I probably have missed something here? Thanks very much for your help!

**Comment by jfcherng** [comment]
I don't use nvim but `settings` is in `initializationOptions`.

**Comment by charliermarsh** [comment]
Yeah that looks right to me.

**Comment by xulongwu4** [comment]
Yes that is right. I need `initializationOptions` for `coc.nvim` and `init_options` for nvim lspconfig. Thanks a lot!

For reference:

coc.nvim:
```json
    "ruff-lsp": {
      "command": "ruff-lsp",
      "filetypes": ["python"],
      "initializationOptions": {
        "settings": {
          "fixAll": false,
          "organizeImports": false
        }
      }
    },
```

nvim lspconfig:
```lua
require("lspconfig").ruff_lsp.setup(
{
          init_options = {
            settings = {
              fixAll = false,
              organizeImports = false,
            },
          },
        },
)
```
