### ISSUE TITLE
Passing --config parameter to Ruff-lsp in Coc-ruff

### ISSUE THREAD

**Issue by bmarcote** [charliermarsh/ruff-lsp#74]
This may be not an issue but rather my lack of experience using Ruff. However, I have been unable to trace what is the current way to fix it.

I have a Ruff config file at `~/.config/ruff.toml`, which I want to use when `ruff-lsp` verifies the code inside NeoVim (using CoC).
The only (most complete) snippet I found in issue #11 is the following:

```
"languageserver": {
  {
    "ruff-lsp": {
      "command": "ruff-lsp",
      "filetypes": ["python"],
      "initializationOptions": {
        "settings": {
          "path": ["~/proj/check-ruff-lsp/venv/bin/ruff"]
        }
      }
    },
  }
}
```

I have tried, without success, to add a parameter under settings like `"config": "~/.config/ruff.toml"`, or inside a possible `"args: []"` parameter.

Is there a way to actually pass the config command to Ruff?

**Comment by charliermarsh** [comment]
Can you try:

```
"languageserver": {
  {
    "ruff-lsp": {
      "command": "ruff-lsp",
      "filetypes": ["python"],
      "initializationOptions": {
        "settings": {
          "path": ["~/proj/check-ruff-lsp/venv/bin/ruff"]
          "args": ["--config", "~/.config/ruff.toml"]
        }
      }
    },
  }
}
```

**Comment by rchl** [comment]
As far as I have tested, ruff doesn't resolve `~` so the path has to be absolute.

```
LSP-ruff: Using environment executable: /Users/rafal/Library/Caches/Sublime Text/Package Storage/LSP-ruff/bin/ruff
LSP-ruff: Running Ruff with: ['/Users/rafal/Library/Caches/Sublime Text/Package Storage/LSP-ruff/bin/ruff', '--no-cache', '--no-fix', '--quiet', '--format', 'json', '-', '--config', '~/ruff.toml', '--stdin-filename', '/usr/local/workspace/sublime-packages/lsp_utils/st3/lsp_utils/electron_runtime.py']
LSP-ruff: error: No such file or directory (os error 2)
```

**Comment by charliermarsh** [comment]
Ah I thought we did, but I guess not for that argument over the CLI. I'll fix it.

**Comment by charliermarsh** [comment]
Fixed in https://github.com/charliermarsh/ruff/pull/3107.

**Comment by yaegassy** [comment]
@bmarcote Hi, I have made an extension for coc.nvim for ruff-lsp. If you need it, please give it a try.

- <https://github.com/yaegassy/coc-ruff>

As with the VS Code extension, the `ruff.executeOrganizeImports` and `ruff.executeAutofix` commands can also be executed, also each setting can also be configured in `coc-settings.json` (global) or `.vim/coc-settings.json` (project local).

**Comment by bmarcote** [comment]
@charliermarsh Thanks! That explains one of the issues. Sorry for not noticing it.
@yaegassy Yes, that' what I am using. Thanks for made the extension by the way!  The previous configuration is my `con-settings.json`.

Even following the pervious suggestion, the `args` part seems to be ignored and thus the config file is not loaded when parsing the code.

**Comment by yaegassy** [comment]
@bmarcote I have configured args in `coc-ruff` and checked the language server logs. The configuration itself seems to be passed correctly.

**coc-settings.json**:

```jsonc
{
  // ...snip
  "ruff.args": [
    "--config", "/Users/yaegassy/.config/ruff.toml"
  ],
  // ...snip
}
```

**LOG**:

> --config settings exists

```
Using environment executable: /private/tmp/ruff-check/venv/bin/ruff
Running Ruff with: ['/private/tmp/ruff-check/venv/bin/ruff', '--no-cache', '--no-fix', '--quiet', '--format', 'json', '-', '--config', '/Users/yaegassy/.config/ruff.toml', '--stdin-filename', '/tmp/ruff-check/main.py']
```

**Comment by bmarcote** [comment]
Completely right. Just my lack of experience here.
I had basically two instances running, and the issues I was seeing were from the other one.

Thank you very much both for the quick feedback and the new commits!

**Comment by yaegassy** [comment]
@bmarcote It seems that the problem has already been resolved, but just in case, it is mentioned as an explanation.

> I had basically two instances running, and the issues I was seeing were from the other one.

With `coc.nvim`, there are two ways to use the language server by registering it directly and starting it, or by installing a dedicated extension and using the language server.

Choose either method to use the language server.
