### ISSUE TITLE
Selectively disable language server features

### ISSUE THREAD

**Issue by cwaldbieser** [charliermarsh/ruff-lsp#78]
I tried using ruff-lsp in neovim as a flake8 replacement-- basically I just wanted the faster diagnostics.  I use the jedi language server for features like format and hover.  However, since I can't selectively disable "hover" for ruff, when I initiate a "hover" on a symbol, jedi pops up the correct info, but ruff prints a "No information available" at the bottom of the screen.

The jedi language server lets you selectively disable various LSP features, which makes it easier to mix and match with other language servers for the same language.

I also tried using ruff with null-ls for diagnostics, but that didn't seem to actually do anything.

**Comment by jfcherng** [comment]
Not sure what exactly you expect but a quick guess here.

Add this to `LSP-ruff.sublime-settings`:
```js
    "disabled_capabilities": {
        "hoverProvider": true,
    },
```
This setting can be used in any LSP-*.

**Comment by rchl** [comment]
@jfcherng wrong repo :)

**Comment by cwaldbieser** [comment]
Sorry if I'm being dense, but are you suggesting that I should be asking for this feature in the ruff project itself?  Or ...?

**Comment by jfcherng** [comment]
my suggestion is irrelevant so I have deleted it.

**Comment by charliermarsh** [comment]
Not sure how best to handle 🤔 VS Code seems to handle this ok, so I guess the behavior varies from client to client, unless I'm mistaken. The issue is that if the hover state is getting in the way with Neovim, then we probably _never_ want to enable the hover behavior in Neovim at all, rather than requiring _every_ Neovim user to disable it.

**Comment by rchl** [comment]
![Screenshot 2023-03-02 at 20 58 07](https://user-images.githubusercontent.com/153197/222538644-968871ed-c0d8-46a8-8db0-00ae61824d3a.png)


```
lua << EOF
  local capabilities = vim.lsp.protocol.make_client_capabilities()
  capabilities.disabled_capabilities.textDocument.hover = true
  -- initialize your LSP client here with the capabilities table
EOF
```

**Comment by cwaldbieser** [comment]
Hmm, "disabled_capabilities" didn't seem to work for me.  I did manage to disable it with something like:

```lua
local function on_attach(client, bufnr)
    local sc = client.server_capabilities
    sc.hoverProvider = false
end

lsp.ruff_lsp.setup {
    on_attach = on_attach
}
```
Using lspconfig.  But I'm not sure if that is a hack or if the API is supposed to work that way.

**Comment by charliermarsh** [comment]
This looks relevant: https://neovim.discourse.group/t/how-to-config-multiple-lsp-for-document-hover/3093

**Comment by charliermarsh** [comment]
E.g., can you set `client.server_capabilities.hoverProvider = false` in the `on_attach`, like so:

```lua
lspconfig['pylsp'].setup({
    enable = true,
    -- disable several capabilities in favor of pyright
    on_attach = function (client, buffer)
        client.server_capabilities.documentFormattingProvider = false
        client.server_capabilities.hoverProvider = false
        client.server_capabilities.renameProvider = false
    end,
    settings = {
        pylsp = {
            configurationSources = { "flake8", "mypy" },
            plugins = {
                flake8 = { enabled = true },
                mypy = { enabled = true },
            },
        },
    },
})
```

**Comment by markis** [comment]
I have been experiencing this exact same issue, and disabling `hoverProvider` in the `on_attach` function fixed it for me.  Is there a way that we could make that part of the code base?  Or does disabling the hoverProvider cause other issues?

**Comment by charliermarsh** [comment]
It doesn't cause other issues -- it's just a convenience thing, the only hover we provide is if you hover over an error code within a `noqa`, we pop up an explanation for the rule (which is useful, and I like, but obviously not nearly as important as Jedi etc.).

Maybe I can make this a default in the Neovim `ruff_lsp`? https://github.com/neovim/nvim-lspconfig/blob/master/doc/server_configurations.md#ruff_lsp

**Comment by charliermarsh** [comment]
Looking into it.

**Comment by charliermarsh** [comment]
Another option is that I only enable this functionality in VS Code and not elsewhere.

**Comment by markis** [comment]
That would make sense.  But it would be disappointing if you added more features to the hover feature, and vim/neovim/etc wouldn't be able to take advantage.

**Comment by markis** [comment]
This might be the solution for neovim: https://github.com/neovim/neovim/issues/20457#issuecomment-1266782345

**Comment by charliermarsh** [comment]
Maybe for now I'll just add this to the Ruff LSP docs.

**Comment by charliermarsh** [comment]
Okay, I added a note for now in #78.

**Comment by 0mm1n** [comment]
If anyone is using [LazyVim](https://github.com/LazyVim/LazyVim), here is the config I added to lua/plugins/ruff.lsp to disable the hover actions for ruff. 

LazyVim has nvim-notify, and it was extremely annoying to see No Information Available pop up every hover.

```lua
local on_attach = function(client, bufnr)
  client.server_capabilities.hoverProvider = false
end

return {
  {
    "neovim/nvim-lspconfig",
    opts = {
      -- you can do any additional lsp server setup here
      -- return true if you don't want this server to be setup with lspconfig
      ---@type table<string, fun(server:string, opts:_.lspconfig.options):boolean?>
      setup = {
        -- Specify * to use this function as a fallback for any server
        -- ["*"] = function(server, opts) end,

        ruff_lsp = function(_, opts)
          -- Configure `ruff-lsp`.
          -- See: https://github.com/neovim/nvim-lspconfig/blob/master/doc/server_configurations.md#ruff_lsp
          -- For the default config, along with instructions on how to customize the settings
          require("lspconfig").ruff_lsp.setup({
            on_attach = on_attach,
            init_options = {
              settings = {
                -- Any extra CLI arguments for `ruff` go here.
                args = {},
              },
            },
          })
          return true
        end,
      },
    },
  },
}
```

**Comment by charliermarsh** [comment]
Thank you for sharing that!

**Comment by chiendo97** [comment]
For anyone using lspconfig:

```lua
require("lspconfig").ruff.setup({
    on_attach = function(client, bufnr)
        client.server_capabilities.documentFormattingProvider = false
        client.server_capabilities.hoverProvider = false
        require("lsp.attach").on_attach(client, bufnr)
    end,
    capabilities = require("lsp.attach").capabilities,
})
```
