### ISSUE TITLE
Is there a way to combine ruff and pyright?

### ISSUE THREAD

**Issue by mpizenberg** [charliermarsh/ruff-lsp#81]
I'm using helix, and I'd be interested in having both ruff and pyright in the editor as they seem complementary. For example, pyright catches missing dependencies, which ruff does not seem to do.

Has someone figured out how to use both in helix?

**Comment by ansipunk** [comment]
I find `ruff-lsp` incomplete in comparison to more advanced tools like `python-lsp-server` with `jedi`, whereas `pylsp` doesn't have code actions, so I use them together.
You should consult with `helix` docs to see how can you use multiple language servers.
This is a part of my `neovim` config where I use `python-lsp-server` for stuff like hover, jump to definition, autocompletion, etc and `ruff-lsp` for style checking and code actions:
```lua
lspconfig.pylsp.setup({
  on_attach = on_attach,
  capabilities = capabilities,
  settings = {
    pylsp = {
      plugins = {
        ruff = { enabled = false },
        autopep8 = { enabled = false },
        flake8 = { enabled = false },
        mccabe = { enabled = false },
        pycodestyle = { enabled = false },
        pydocstyle = { enabled = false },
        pyflakes = { enabled = false },
        pylint = { enabled = false },
        yapf = { enabled = false },
      },
    },
  },
})

lspconfig.ruff_lsp.setup({
  on_attach = on_attach,
  capabilities = capabilities,
})
```

**Comment by charliermarsh** [comment]
> I'm using helix, and I'd be interested in having both ruff and pyright in the editor as they seem complementary. For example, pyright catches missing dependencies, which ruff does not seem to do.

Yeah, it's definitely the case that Ruff is intended to be used alongside another LSP, e.g. Pyright, or Jedi, or something that can do general auto-completion and jump-to-completion and so on -- since Ruff only does lint validation.

I don't think Helix supports multiple LSP servers per language unfortunately... @messense built something to enable this, specifically for Ruff and Pyright: https://github.com/messense/multi-lsp-proxy. It might work for your use case! I haven't tested it personally so can't say definitively.

**Comment by NeilGirdhar** [comment]
@ansipunk Would you mind sharing your `capabilities` and `on_attach`?   I'm new to neovim and trying to get everything set up.  Thanks.

**Comment by ansipunk** [comment]
@NeilGirdhar 
```lua
local lspconfig = require('lspconfig')
local langservers = { 'zls', 'golangci_lint_ls', 'ruff_lsp' }
local capabilities = require('cmp_nvim_lsp').default_capabilities()
local illuminate = require('illuminate')
local on_attach = function(client) illuminate.on_attach(client) end

for _, langserver in ipairs(langservers) do
    lspconfig[langserver].setup({
        capabilities = capabilities,
        on_attach = on_attach,
        single_file_support = true,
    })
end
```
Here I use plugins `cmp_nvim_lsp` for completions from language servers and `illuminate` for highlighting tokens according to the actual syntax tree, so it is way more intelligent. Default settings, completions and keybindidngs may be found at `cmp_nvim_lsp` GitHub page README.
