### ISSUE TITLE
aerial.nvim doesn't show all of symbols when using ruff-lsp

### ISSUE THREAD

**Issue by nhuhoang0701** [charliermarsh/ruff-lsp#88]
I always open the symbol outline when I code. However, it seems that the symbol outline generated by aerial.nvim only displays class names and functions without their attributes or local variables:

![image](https://user-images.githubusercontent.com/40765474/226476493-10cc8fe4-d346-43e9-a089-32bfd871e2f5.png)

However, the symbol outline works normally when I use Pyright instead:
![image](https://user-images.githubusercontent.com/40765474/226476764-2ede5f94-1540-42bb-ba75-d93133508166.png)

I use Arch Linux, AstroNvim v2.0 and ruff-lsp v0.0.23

**Comment by charliermarsh** [comment]
Ruff is intended to be used alongside another LSP, like Pyright, since Ruff only handles linter diagnostic and autofixes (and not general LSP operations like "Go-To Symbol"). Are you using Ruff alongside Pyright? Do you see this with both enabled at once?

**Comment by nhuhoang0701** [comment]
Ok I see, I thought Rulff can fully replace Pyright and handle those LSP operations because I was looking for a lightweight alternative tool for Pyright. The symbol outline works fine when both are enabled at once.
