### ISSUE TITLE
Crashes at startup

### ISSUE THREAD

**Issue by WhyNotHugo** [charliermarsh/ruff-lsp#97]
ruff-lsp has been crashing at startup for a few days for me. I though it might be an issue with my neovim setup, but apparently it's something else:

```console
> ruff-lsp --version
Traceback (most recent call last):
  File "/usr/bin/ruff-lsp", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/usr/lib/python3.11/site-packages/ruff_lsp/__main__.py", line 5, in main
    from ruff_lsp import __version__, server
  File "/usr/lib/python3.11/site-packages/ruff_lsp/server.py", line 325, in <module>
    @LSP_SERVER.feature(
     ^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/pygls/feature_manager.py", line 174, in decorator
    raise TypeError(
TypeError: Options of method "textDocument/codeAction" should be instance of type <class 'lsprotocol.types.CodeActionOptions'>
```

Versions:

```console
> apk list --installed | grep ruff
ruff-0.0.261-r0 x86_64 {ruff} (MIT) [installed]
ruff-lsp-0.0.24-r0 x86_64 {ruff-lsp} (MIT) [installed]
ruff-zsh-completion-0.0.261-r0 x86_64 {ruff} (MIT) [installed]

> apk list --installed | grep py3-gls
py3-gls-1.0.1-r0 x86_64 {py3-gls} (Apache-2.0) [installed]


> python --version
Python 3.11.3

```

**Comment by charliermarsh** [comment]
Oh interesting, will try to repro with that set of deps. Did you upgrade anything (e.g. the Ruff version) that might’ve trigger this, to give me a lead?

**Comment by WhyNotHugo** [comment]
I think ruff-lsp updated last. Regrettably, I don't have logs of upgraded packages.

These are distribution binary packages, so you can repro on an Alpine container.

They're honestly unpatched upstream stable releases:

https://gitlab.alpinelinux.org/alpine/aports/-/blob/master/testing/ruff/APKBUILD
https://gitlab.alpinelinux.org/alpine/aports/-/blob/master/testing/ruff-lsp/APKBUILD
https://gitlab.alpinelinux.org/alpine/aports/-/blob/master/testing/py3-gls/APKBUILD

I can also repro this with the `main` branch:

    > python -m ruff_lsp -- --version
    Traceback (most recent call last):
      File "<frozen runpy>", line 198, in _run_module_as_main
      File "<frozen runpy>", line 88, in _run_code
      File "/home/hugo/src/github.com/charliermarsh/ruff-lsp/ruff_lsp/__main__.py", line 19, in <module>
        main()
      File "/home/hugo/src/github.com/charliermarsh/ruff-lsp/ruff_lsp/__main__.py", line 5, in main
        from ruff_lsp import __version__, server
      File "/home/hugo/src/github.com/charliermarsh/ruff-lsp/ruff_lsp/server.py", line 325, in <module>
        @LSP_SERVER.feature(
         ^^^^^^^^^^^^^^^^^^^
      File "/usr/lib/python3.11/site-packages/pygls/feature_manager.py", line 174, in decorator
        raise TypeError(
    TypeError: Options of method "textDocument/codeAction" should be instance of type <class 'lsprotocol.types.CodeActionOptions'>

-- 
Hugo

**Comment by charliermarsh** [comment]
No worries — this is plenty to go off of. I’m in transit today for PyCon but I’ll try to prioritize this when I’m able to do some focused work.

**Comment by nekopsykose** [comment]
was actually a gls/lsprotocol issue

**Comment by charliermarsh** [comment]
Does it exist in the most recently released version?

**Comment by nekopsykose** [comment]
of latest pygls, yes, at the same time as latest lsprotocol. either one needs an older lsprotocol (2022.x) or to wait for next pygls release (in terms of what you get from pypi).

**Comment by nekopsykose** [comment]
unless i'm mistaken, the exact recommended locked deps:

```

lsprotocol==2023.0.0a1
    # via
    #   pygls
    #   ruff-lsp (pyproject.toml)
pygls==1.0.1
    # via ruff-lsp (pyproject.toml)
```

would reproduce the same issue (since those are the incompatible versions). but then i'd expect more people to have it broken via pip install, so maybe there's actually a third missing piece here too :)

**Comment by charliermarsh** [comment]
Ok, so I can reproduce the crash by running `pip install .` then `pip install --upgrade typeguard` then `python -m ruff_lsp`.

**Comment by charliermarsh** [comment]
How would your environment end up with a version of `typeguard` greater than 3 though?

**Comment by WhyNotHugo** [comment]
Alpine ships `py3-typeguard-3.0.2`. Perhaps I should have reported this one downstream first.

**Comment by charliermarsh** [comment]
Ah no worries. Should I close then? Anything we can do on the LSP side?

**Comment by WhyNotHugo** [comment]
I think it's okay to close this; this doesn't seem to be an issue with the LSP.

For my own understanding (and so this can be addressed in the right place), this is an issue in `pygls` itself, right? I don't see any trivial workaround.

**Comment by nekopsykose** [comment]
it's already fixed in pygls master, i backported the relevant commit on our side

**Comment by WhyNotHugo** [comment]
Thanks both!
